// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqcucdvqtwwrfyougvfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xY3VjZHZxdHd3cmZ5b3VndmZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4Mjc3MzQsImV4cCI6MjA1ODQwMzczNH0.3SCRVusCIUj84UE1b2CSqXD42ffKaVGJ6ipeKFNbp-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);